# Generated by Django 5.2.1 on 2025-06-21 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('college_in_out_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeinoutlog',
            name='marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college_log_marked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collegeinoutlog',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='college_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
