# Generated by Django 5.2.1 on 2025-06-21 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0002_initial'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timetableimage',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_images_uploaded', to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='timetableimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('batch', 'day', 'start_time', 'subject', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableimage',
            unique_together={('batch', 'term', 'effective_date')},
        ),
    ]
