# Generated by Django 5.2.1 on 2025-08-02 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerecord_unique_together_and_more'),
        ('timetable', '0004_classsession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timetables_old', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TimetableFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, help_text="e.g., 'Semester 1', 'Annual'", max_length=50, null=True)),
                ('effective_date', models.DateField(blank=True, help_text='Date from which this timetable is effective', null=True)),
                ('file', models.FileField(help_text='Upload timetable as image, PDF, or Excel file', upload_to='timetable_files/')),
                ('file_type', models.CharField(choices=[('image', 'Image (PNG, JPG, JPEG)'), ('pdf', 'PDF Document'), ('excel', 'Excel File (XLS, XLSX)')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, help_text='Optional title for the timetable', max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this timetable is currently active')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_files', to='attendance.batch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_timetables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
