# Generated by Django 5.2.1 on 2025-07-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('bulk_action', 'Bulk Action')], max_length=20)),
                ('model_name', models.CharField(help_text='Name of the model being acted upon', max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object being acted upon', max_length=100, null=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Activity Log',
                'verbose_name_plural': 'Admin Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CodeModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the modified file', max_length=500)),
                ('file_type', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('config', 'Configuration')], max_length=20)),
                ('modification_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore')], max_length=20)),
                ('old_content', models.TextField(blank=True, help_text='Previous content before modification')),
                ('new_content', models.TextField(blank=True, help_text='New content after modification')),
                ('description', models.TextField(help_text='Description of what was changed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_applied', models.BooleanField(default=True, help_text='Whether the modification was successfully applied')),
                ('error_message', models.TextField(blank=True, help_text='Error message if modification failed')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code Modification Log',
                'verbose_name_plural': 'Code Modification Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_duration', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this session is still active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login History',
                'verbose_name_plural': 'Login History',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_created', 'User Created'), ('user_modified', 'User Modified'), ('user_deleted', 'User Deleted'), ('payment_generated', 'Payment Generated'), ('attendance_marked', 'Attendance Marked'), ('grade_uploaded', 'Grade Uploaded'), ('leave_approved', 'Leave Approved'), ('bulletin_posted', 'Bulletin Posted'), ('system_backup', 'System Backup'), ('code_modified', 'Code Modified')], max_length=50)),
                ('description', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
